#!/usr/bin/env node
// Renders the Homebrew formula for a release: `node scripts/release/formula.mjs <version> <sha256>`.
// Mirrors the tap layout ynh uses (Formula/<name>.rb in github.com/eyelock/homebrew-tap).
const [version, sha256] = process.argv.slice(2);
if (!version || !/^[0-9a-f]{64}$/.test(sha256 ?? "")) {
  console.error("usage: formula.mjs <version> <sha256>");
  process.exit(2);
}
process.stdout.write(`# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class Ynm < Formula
  desc "Your named memory: agent memory in git notes over MCP and CLI"
  homepage "https://github.com/eyelock/ynm"
  url "https://github.com/eyelock/ynm/releases/download/v${version}/ynm-${version}.tar.gz"
  sha256 "${sha256}"
  version "${version}"
  license "MIT"

  depends_on "git"
  depends_on "node"

  def install
    libexec.install Dir["*"]
    (bin/"ynm").write_env_script libexec/"bin/run.js", PATH: "#{Formula["node"].opt_bin}:$PATH"
  end

  test do
    assert_match "@ynm/cli", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
`);
