#!/usr/bin/env node
// Renders a Homebrew formula from a release manifest (scripts/release/manifest.mjs):
//   node scripts/release/formula.mjs <manifest.json> ynm        standalone binaries, needs git
//   node scripts/release/formula.mjs <manifest.json> ynm-slim   the bundle on Homebrew's node
// Mirrors the tap layout ynh uses (Formula/<name>.rb in github.com/eyelock/homebrew-tap); the
// standalone formula has ynh's per-platform on_macos / on_linux shape.
import { readFileSync } from "node:fs";

const [manifestPath, which] = process.argv.slice(2);
if (!manifestPath || !["ynm", "ynm-slim"].includes(which ?? "")) {
  console.error("usage: formula.mjs <manifest.json> ynm|ynm-slim");
  process.exit(2);
}
const { version, assets } = JSON.parse(readFileSync(manifestPath, "utf8"));
const download = (file) => `https://github.com/eyelock/ynm/releases/download/v${version}/${file}`;
const DESC = "Your named memory: agent memory in git notes over MCP and CLI";

function asset(kind, os, arch) {
  const a = assets.find((x) => x.kind === kind && x.os === os && x.arch === arch);
  if (!a) {
    console.error(`manifest has no ${kind} asset for ${os}/${arch}`);
    process.exit(1);
  }
  return a;
}

function platform(os, arch, cond) {
  const a = asset("standalone", os, arch);
  return `    if ${cond}
      url "${download(a.file)}"
      sha256 "${a.sha256}"

      define_method(:install) do
        bin.install "ynm"
      end
    end`;
}

const header = (klass) => `# typed: false
# frozen_string_literal: true

# This file is generated by the ynm release workflow. DO NOT EDIT.
class ${klass} < Formula
  desc "${DESC}"
  homepage "https://github.com/eyelock/ynm"`;

const test = `  test do
    assert_match "@ynm/cli/#{version}", shell_output("#{bin}/ynm --version")
    system "#{bin}/ynm", "serve", "--help"
  end
end
`;

if (which === "ynm") {
  process.stdout.write(`${header("Ynm")}
  version "${version}"
  license "MIT"

  depends_on "git"

  conflicts_with "ynm-slim", because: "both install a \`ynm\` executable"

  on_macos do
${platform("darwin", "amd64", "Hardware::CPU.intel?")}
${platform("darwin", "arm64", "Hardware::CPU.arm?")}
  end

  on_linux do
${platform("linux", "amd64", "Hardware::CPU.intel? && Hardware::CPU.is_64_bit?")}
${platform("linux", "arm64", "Hardware::CPU.arm? && Hardware::CPU.is_64_bit?")}
  end

${test}`);
} else {
  const a = asset("slim", "any", "any");
  process.stdout.write(`${header("YnmSlim")}
  url "${download(a.file)}"
  sha256 "${a.sha256}"
  version "${version}"
  license "MIT"

  depends_on "git"
  depends_on "node"

  conflicts_with "ynm", because: "both install a \`ynm\` executable"

  def install
    libexec.install "ynm.mjs"
    bin.install "bin/ynm"
    # Run on Homebrew's node, whatever node is first on PATH.
    inreplace bin/"ynm", 'node="\${YNM_NODE:-node}"',
              "node=\\"\\\${YNM_NODE:-#{Formula["node"].opt_bin}/node}\\""
  end

${test}`);
}
