// Writes src/version.ts from package.json so the version is compiled in, not read at runtime
// (a bundled binary has no package.json beside it).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
const { version } = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const file = new URL("../src/version.ts", import.meta.url);
const text = `// Generated by scripts/version.mjs at build time; do not edit.\nexport const MCP_VERSION = "${version}";\n`;
if (!existsSync(file) || readFileSync(file, "utf8") !== text) writeFileSync(file, text);
