// Regenerates the generated parts of the docs from the built packages, and checks links.
//
//   node scripts/gen-docs.mjs                 write into docs/
//   node scripts/gen-docs.mjs --out <dir>     write the same files under <dir> (drift test)
//   node scripts/gen-docs.mjs --check-links   report broken relative links and anchors; exit 1
//
// Fully generated: docs/reference/cli.md, docs/reference/mcp.md, docs/tutorial/manual-test-plan.md.
// Partly generated: the regions between `<!-- gen:NAME -->` and `<!-- /gen:NAME -->` in
// docs/reference/{configuration,record-format,memory-types}.md; the prose around them is edited
// by hand. Output is deterministic: no dates, sorted inputs. Needs `pnpm build` first.
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const docs = join(root, "docs");
const load = (rel) => import(pathToFileURL(join(root, rel)).href);
const requireFromService = createRequire(join(root, "packages", "service", "package.json"));
const { z } = await import(pathToFileURL(requireFromService.resolve("zod")).href);

const GENERATED_NOTE =
  "<!-- Generated by scripts/gen-docs.mjs from the built packages. Do not edit; run `make docs-gen`. -->";

// ---------------------------------------------------------------------------------------------
// Shared rendering helpers

const code = (s) => `\`${String(s).replace(/`/g, "'")}\``;
const cell = (s) =>
  String(s ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ");
const table = (head, rows) =>
  [
    `| ${head.join(" | ")} |`,
    `|${head.map(() => "---").join("|")}|`,
    ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`),
  ].join("\n");
const toKebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const jsonSchema = (schema) => z.toJSONSchema(schema, { io: "input", unrepresentable: "any" });

/** Drops `null` from `anyOf` (nullable fields) and reports it. */
function unwrap(s) {
  if (s?.anyOf) {
    const rest = s.anyOf.filter((x) => x.type !== "null");
    if (rest.length === 1)
      return {
        ...rest[0],
        description: s.description ?? rest[0].description,
        default: s.default ?? rest[0].default,
        nullable: rest.length < s.anyOf.length,
      };
  }
  return s ?? {};
}

function range(s) {
  const big = (n) => n === undefined || Math.abs(n) >= Number.MAX_SAFE_INTEGER;
  let lo = s.minimum ?? (s.exclusiveMinimum === 0 && s.type === "integer" ? 1 : undefined);
  const hi = big(s.maximum) ? undefined : s.maximum;
  if (big(lo)) lo = undefined;
  if (s.exclusiveMinimum !== undefined && lo === undefined) return ` > ${s.exclusiveMinimum}`;
  if (lo !== undefined && hi !== undefined) return ` ${lo}..${hi}`;
  if (lo !== undefined) return ` >= ${lo}`;
  if (hi !== undefined) return ` <= ${hi}`;
  return "";
}

/** A short, readable type for a JSON Schema node. */
function typeText(raw) {
  const s = unwrap(raw);
  let t;
  if (s.enum) t = s.enum.map((v) => code(v)).join(" | ");
  else if (s.const !== undefined) t = code(JSON.stringify(s.const));
  else if (s.type === "array") {
    const item = unwrap(s.items);
    t = `array of ${item.type === "object" ? "object" : typeText(item)}`;
  } else if (s.type === "object") t = "object";
  else if (s.type === "string") {
    t = s.format === "date-time" ? "date-time" : "string";
    if (s.maxLength !== undefined) t += ` (max ${s.maxLength})`;
  } else if (s.type === "integer" || s.type === "number") t = `${s.type}${range(s)}`;
  else if (s.type === "boolean") t = "boolean";
  else t = "any";
  return s.nullable ? `${t} or null` : t;
}

function defaultText(v) {
  if (v === undefined) return "";
  if (typeof v === "string") return code(v);
  return code(JSON.stringify(v));
}

/**
 * Flattens an object schema into rows. Arrays of objects and nested objects expand into
 * `parent[].child` and `parent.child` rows. `defaults` is the parsed empty value, used where a
 * default sits on a parent object rather than on the leaf.
 */
function schemaRows(json, { prefix = "", defaults, expand = true } = {}) {
  const rows = [];
  const required = new Set(json.required ?? []);
  for (const [name, raw] of Object.entries(json.properties ?? {})) {
    const s = unwrap(raw);
    const path = `${prefix}${name}`;
    const dflt = s.default !== undefined ? s.default : defaults?.[name];
    const isObject = s.type === "object" && s.properties;
    const isObjArray = s.type === "array" && unwrap(s.items).type === "object";
    const description = s.description ?? "";
    rows.push({
      name: path,
      type: typeText(s),
      required: required.has(name) && s.default === undefined,
      default: isObject ? undefined : dflt,
      description,
      documented: s.description !== undefined,
    });
    if (expand && isObject)
      rows.push(
        ...schemaRows(s, {
          prefix: `${path}.`,
          defaults: dflt && typeof dflt === "object" ? dflt : undefined,
        })
      );
    if (expand && isObjArray)
      rows.push(...schemaRows(unwrap(s.items), { prefix: `${path}[].` }));
  }
  return rows;
}

// ---------------------------------------------------------------------------------------------
// CLI reference

/**
 * Strips the type suffixes flagsFromSchema appends, and drops a description that is only the
 * field name (flagsFromSchema's fallback when the schema has none).
 */
function flagDescription(flag, description = "") {
  const d = description.replace(/( \((JSON array|JSON object|number|default: [^)]*)\))+$/, "");
  const bare = d.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
  return bare === flag ? "" : d;
}

async function cliReference() {
  const dir = join(root, "packages", "cli", "dist", "commands");
  const { YnmCommand } = await load("packages/cli/dist/lib/base.js");
  const { TOOL_SPECS } = await load("packages/service/dist/tools.js");
  const { RecordFilterSchema } = await load("packages/model/dist/index.js");
  const base = YnmCommand.baseFlags;
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".js"))
    .sort();
  const out = [
    GENERATED_NOTE,
    "",
    "# CLI reference",
    "",
    "Every `ynm` command, generated from the command definitions. `ynm <command> --help` prints the",
    "same flags. Flags generated from a tool's input schema show that schema's default; the MCP tool",
    "with the same input is listed in the [MCP reference](mcp.md).",
    "",
    "## Common flags",
    "",
    table(
      ["Flag", "Type", "Default", "Description"],
      [
        ["`--json`", "boolean", code("false"), base.json.description],
        ["`--cwd <value>`", "string", "", base.cwd.description],
      ]
    ),
    "",
    "Every command except `serve` takes both; `serve` takes `--cwd` only. Exit codes and the JSON",
    "shapes are in [Exit codes and JSON output](exit-codes-and-json.md).",
    "",
    "## Commands",
    "",
    "__INDEX__",
    "",
  ];
  const indexRows = [];
  for (const f of files) {
    const id = f.replace(/\.js$/, "");
    const C = (await load(`packages/cli/dist/commands/${f}`)).default;
    const tool = TOOL_SPECS.find((t) => t.command === id);
    const schema = tool?.input ?? (id === "list" || id === "export" ? RecordFilterSchema : null);
    const props = schema ? (jsonSchema(schema).properties ?? {}) : {};
    const propByFlag = new Map(Object.entries(props).map(([k, v]) => [toKebab(k), unwrap(v)]));
    indexRows.push([`[\`${id}\`](#ynm-${id})`, C.description ?? ""]);

    const args = Object.entries(C.args ?? {});
    const flags = Object.entries(C.flags ?? {});
    const common = flags.filter(([, fl]) => fl === base.json || fl === base.cwd);
    const own = flags.filter(([, fl]) => fl !== base.json && fl !== base.cwd);
    const usage = [
      "ynm",
      id,
      ...args.map(([n, a]) => (a.required ? `<${n}>` : `[${n}]`)),
      ...(own.length || common.length ? ["[flags]"] : []),
    ].join(" ");

    out.push(`## ynm ${id}`, "", C.description ?? "", "", "```text", usage, "```", "");
    if (args.length) {
      out.push(
        table(
          ["Argument", "Required", "Values", "Description"],
          args.map(([n, a]) => [
            code(n),
            a.required ? "yes" : "no",
            (a.options ?? []).map(code).join(", "),
            a.description ?? "",
          ])
        ),
        ""
      );
    }
    if (own.length) {
      const rows = own.map(([n, fl]) => {
        const prop = propByFlag.get(n);
        let type;
        if (fl.type === "boolean") type = "boolean";
        else if (fl.options) type = fl.options.map(code).join(" | ");
        else if (prop?.type === "array" && fl.multiple) type = typeText(prop.items);
        else if (prop?.type === "array") type = "JSON array";
        else if (prop?.type === "object") type = "JSON object";
        else if (prop) type = typeText(prop);
        else if (String(fl.parse).includes("Expected an integer")) type = "integer";
        else type = "string";
        if (fl.multiple) type += ", repeatable";
        const name =
          fl.type === "boolean"
            ? fl.allowNo
              ? `\`--[no-]${n}\``
              : `\`--${n}\``
            : `\`--${n} <value>\``;
        const dflt = fl.default !== undefined ? fl.default : prop?.default;
        return [
          name,
          type,
          fl.required ? "yes" : "",
          defaultText(dflt),
          flagDescription(n, fl.description),
        ];
      });
      out.push(table(["Flag", "Type", "Required", "Default", "Description"], rows), "");
    }
    if (common.length) out.push(`Common flags: ${common.map(([n]) => `\`--${n}\``).join(", ")}.`, "");
    if (tool) out.push(`MCP tool: [\`${tool.name}\`](mcp.md#${tool.name}).`, "");
    const examples = (C.examples ?? []).map((e) =>
      String(typeof e === "string" ? e : e.command)
        .replace(/<%= config\.bin %>/g, "ynm")
        .replace(/<%= command\.id %>/g, id)
    );
    if (examples.length) out.push("Examples:", "", "```bash", ...examples, "```", "");
  }
  out[out.indexOf("__INDEX__")] = table(["Command", "Description"], indexRows);
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

// ---------------------------------------------------------------------------------------------
// MCP reference

async function mcpReference() {
  const { createYnmServer } = await load("packages/mcp/dist/server.js");
  const { TOOL_SPECS } = await load("packages/service/dist/tools.js");
  const server = createYnmServer({ cwd: root }, async () => {
    throw new Error("the docs generator never opens a store");
  });
  const tools = server._registeredTools;
  const resources = server._registeredResources;
  const templates = server._registeredResourceTemplates;
  const prompts = server._registeredPrompts;
  const instructions = server.server?._instructions;
  if (!tools || !resources || !templates || !prompts || !instructions)
    throw new Error("McpServer internals changed; update mcpReference in scripts/gen-docs.mjs");

  const out = [
    GENERATED_NOTE,
    "",
    "# MCP reference",
    "",
    "What `ynm serve` exposes to an MCP client: ten tools, four resources and three prompts,",
    "generated from the server definition. Every tool has a CLI command with the same input; see",
    "the [CLI reference](cli.md).",
    "",
    "## Server instructions",
    "",
    "Sent to the client in the `initialize` result:",
    "",
    ...instructions.split("\n").map((l) => `> ${l}`),
    "",
    "## Tools",
    "",
    table(
      ["Tool", "CLI command", "Read-only", "Destructive"],
      TOOL_SPECS.map((t) => {
        const a = tools[t.name]?.annotations ?? {};
        return [
          `[\`${t.name}\`](#${t.name})`,
          `[\`ynm ${t.command}\`](cli.md#ynm-${t.command})`,
          a.readOnlyHint ? "yes" : "no",
          a.destructiveHint ? "yes" : "no",
        ];
      })
    ),
    "",
    "A tool result carries the payload as JSON text and as `structuredContent: { data, guidance }`.",
    "When `guidance` is set it is also appended to the text after a blank line as",
    "`Guidance: ...`. A failed call returns `isError: true` with the message as text.",
    "",
  ];
  for (const t of TOOL_SPECS) {
    const rows = schemaRows(jsonSchema(t.input));
    out.push(`### ${t.name}`, "", t.description, "", `CLI: \`ynm ${t.command}\`.`, "");
    if (rows.length)
      out.push(
        table(
          ["Field", "Type", "Required", "Default", "Description"],
          rows.map((r) => [
            code(r.name),
            r.type,
            r.required ? "yes" : "",
            defaultText(r.default),
            r.description,
          ])
        ),
        ""
      );
    else out.push("No input fields.", "");
  }
  out.push(
    "## Resources",
    "",
    table(
      ["URI", "MIME type", "Description"],
      [
        ...Object.entries(resources).map(([uri, r]) => [
          code(uri),
          code(r.metadata?.mimeType ?? ""),
          r.metadata?.description ?? "",
        ]),
        ...Object.values(templates).map((r) => [
          code(r.resourceTemplate.uriTemplate?.toString?.() ?? r.resourceTemplate._uriTemplate.template),
          code(r.metadata?.mimeType ?? ""),
          `${r.metadata?.description ?? ""} (template)`,
        ]),
      ]
    ),
    "",
    "## Prompts",
    "",
    "Each prompt takes no arguments and returns one user message holding a guidance document. The",
    "same documents are written into client instructions by `ynm client install`.",
    "",
    table(
      ["Prompt", "Description"],
      Object.entries(prompts).map(([name, p]) => [code(name), p.description ?? ""])
    ),
    ""
  );
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

// ---------------------------------------------------------------------------------------------
// Partly generated reference pages

function keyTable(rows) {
  return table(
    ["Key", "Type", "Default", "Description"],
    rows.map((r) => [
      code(r.name),
      r.type,
      r.name === "redaction" ? "[six patterns](#default-redaction-patterns)" : defaultText(r.default),
      r.description,
    ])
  );
}

async function configurationBlocks() {
  const { YnmConfigSchema, DEFAULT_REDACTION } = await load("packages/service/dist/config.js");
  const { DreamConfigSchema } = await load("packages/model/dist/index.js");
  const json = jsonSchema(YnmConfigSchema);
  const defaults = YnmConfigSchema.parse({});
  const top = schemaRows({ ...json, properties: { ...json.properties, dream: undefined } }, {
    defaults,
  }).filter((r) => r.name !== "dream");
  const dreamJson = jsonSchema(DreamConfigSchema);
  const dream = schemaRows(dreamJson, {
    prefix: "dream.",
    defaults: DreamConfigSchema.parse({}),
  });
  return {
    "config-keys": keyTable(top),
    "dream-keys": keyTable(dream),
    "redaction-defaults": ["```text", ...DEFAULT_REDACTION, "```"].join("\n"),
  };
}

async function recordBlocks() {
  const m = await load("packages/model/dist/index.js");
  const rows = schemaRows(jsonSchema(m.MemoryRecordSchema));
  return {
    "record-fields": table(
      ["Field", "Type", "Required", "Description"],
      rows.map((r) => [code(r.name), r.type, r.required ? "yes" : "", r.description])
    ),
    ops: m.OPS.map((o) => `- ${code(o)}`).join("\n"),
    relations: m.RELATIONS.map((o) => `- ${code(o)}`).join("\n"),
  };
}

async function memoryTypeBlocks() {
  const r = await load("packages/index/dist/ranker.js");
  const { MEMORY_TYPES } = await load("packages/model/dist/index.js");
  const w = [
    ["with `text`", r.WEIGHTS_WITH_TEXT],
    ["filter only", r.WEIGHTS_FILTER_ONLY],
  ];
  return {
    "half-lives": table(
      ["Type", "Recency half-life (days)"],
      MEMORY_TYPES.map((t) => [code(t), r.HALF_LIFE_DAYS[t] ?? "none (no decay)"])
    ),
    weights: table(
      ["Query", "relevance", "recency", "importance", "pinned"],
      w.map(([q, x]) => [q, x.relevance, x.recency, x.importance, x.pinned])
    ),
  };
}

function fillBlocks(markdown, blocks, file) {
  let text = markdown;
  for (const [name, body] of Object.entries(blocks)) {
    const re = new RegExp(`(<!-- gen:${name} -->)[\\s\\S]*?(<!-- /gen:${name} -->)`);
    if (!re.test(text)) throw new Error(`${file}: missing <!-- gen:${name} --> block`);
    text = text.replace(re, (_, a, b) => `${a}\n${body}\n${b}`);
  }
  return text;
}

// ---------------------------------------------------------------------------------------------
// Manual test plan

/** docsify's heading slug: lowercased, punctuation dropped, spaces to dashes, per-page counter. */
function slugger() {
  const seen = new Map();
  return (heading) => {
    let slug = heading
      .trim()
      .replace(/`/g, "")
      .toLowerCase()
      .replace(/<[^>]+>/g, "")
      .replace(/[ -⁯⸀-⹿\\'!"#$%&()*+,./:;<=>?@[\]^`{|}~]/g, "")
      .replace(/\s/g, "-")
      .replace(/-+/g, "-")
      .replace(/^(\d)/, "_$1");
    const n = seen.has(slug) ? seen.get(slug) + 1 : 0;
    seen.set(slug, n);
    if (n) slug = `${slug}-${n}`;
    return slug;
  };
}

function headingsOf(markdown) {
  const out = [];
  let fence = false;
  for (const line of markdown.split("\n")) {
    if (/^\s*```/.test(line)) fence = !fence;
    if (fence) continue;
    const h = /^(#{1,6})\s+(.*?)\s*#*\s*$/.exec(line);
    if (h) out.push({ level: h[1].length, text: h[2] });
  }
  return out;
}

function manualTestPlan() {
  const dir = join(docs, "tutorial");
  const files = readdirSync(dir)
    .filter((f) => /^\d{2}-.*\.md$/.test(f))
    .sort();
  const out = [
    GENERATED_NOTE,
    "",
    "# Manual test plan",
    "",
    "Every step of every tutorial, in order, with a link to it. Run the tutorials top to bottom to",
    "cover the happy path; tick steps off here when testing by hand. A model can run the same steps",
    "for you; see [Running tutorials as evals](RUNNING.md).",
    "",
    "Steps marked with a condition need a key or an optional tool and may be skipped.",
    "",
  ];
  for (const f of files) {
    const n = Number(f.slice(0, 2));
    const lines = readFileSync(join(dir, f), "utf8").split("\n");
    const slug = slugger();
    let title = f;
    let heading = null;
    let pendingSkip;
    const rows = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const h = /^(#{1,6})\s+(.*?)\s*$/.exec(line);
      if (h) {
        const anchor = slug(h[2]);
        if (h[1].length === 1) title = h[2];
        else heading = { text: h[2], anchor, blocks: 0 };
        continue;
      }
      const skip = /^<!--\s*tutorial:\s*skip unless\s+([A-Z0-9_]+)\s*-->$/.exec(line.trim());
      if (skip) {
        pendingSkip = skip[1];
        continue;
      }
      if (/^\s*```/.test(line)) {
        const body = [];
        for (i += 1; i < lines.length && lines[i].trim() !== "```"; i++) body.push(lines[i]);
        if (line.trim() === "```bash" && heading) {
          heading.blocks += 1;
          const first = body.map((l) => l.trim()).find((l) => l && !l.startsWith("#")) ?? "";
          rows.push([
            `${n}.${rows.length + 1}`,
            `[${heading.text}${heading.blocks > 1 ? ` (${heading.blocks})` : ""}](${f}#${heading.anchor})`,
            first ? code(first.length > 72 ? `${first.slice(0, 69)}...` : first) : "",
            pendingSkip ? `needs ${code(pendingSkip)}` : "",
          ]);
        }
        pendingSkip = undefined;
        continue;
      }
      if (line.trim() !== "") pendingSkip = undefined;
    }
    out.push(
      `## [${title}](${f})`,
      "",
      table(["#", "Step", "First command", "Condition"], rows),
      ""
    );
  }
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

// ---------------------------------------------------------------------------------------------
// Link checker

function markdownFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...markdownFiles(p));
    else if (name.endsWith(".md")) out.push(p);
  }
  return out;
}

/** Relative links and anchors in docs/ must resolve. Root-absolute links resolve from docs/. */
function checkLinks() {
  const anchors = new Map();
  const anchorsOf = (file) => {
    if (!anchors.has(file)) {
      const slug = slugger();
      anchors.set(file, new Set(headingsOf(readFileSync(file, "utf8")).map((h) => slug(h.text))));
    }
    return anchors.get(file);
  };
  const broken = [];
  for (const file of markdownFiles(docs)) {
    const text = readFileSync(file, "utf8")
      .replace(/```[\s\S]*?```/g, "")
      .replace(/`[^`\n]*`/g, "");
    for (const m of text.matchAll(/\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)) {
      const target = m[1];
      if (/^[a-z]+:/i.test(target) || target.startsWith("//")) continue;
      const [path, anchor] = target.split("#");
      const dest = path
        ? path.startsWith("/")
          ? join(docs, path)
          : resolve(dirname(file), path)
        : file;
      const where = relative(root, file);
      let exists = false;
      try {
        exists = statSync(dest).isFile() || statSync(dest).isDirectory();
      } catch {}
      if (!exists) {
        broken.push(`${where}: ${target} (no such file)`);
        continue;
      }
      if (anchor && dest.endsWith(".md") && !anchorsOf(dest).has(anchor))
        broken.push(`${where}: ${target} (no such heading)`);
    }
  }
  return broken;
}

// ---------------------------------------------------------------------------------------------
// Main

const argv = process.argv.slice(2);
if (argv.includes("--check-links")) {
  const broken = checkLinks();
  for (const b of broken) console.error(b);
  console.log(broken.length ? `${broken.length} broken links` : "links ok");
  process.exit(broken.length ? 1 : 0);
}
const outIdx = argv.indexOf("--out");
const outDir = outIdx >= 0 ? resolve(argv[outIdx + 1]) : docs;

const partial = {
  "reference/configuration.md": await configurationBlocks(),
  "reference/record-format.md": await recordBlocks(),
  "reference/memory-types.md": await memoryTypeBlocks(),
};
const files = {
  "reference/cli.md": await cliReference(),
  "reference/mcp.md": await mcpReference(),
  "tutorial/manual-test-plan.md": manualTestPlan(),
};
for (const [rel, blocks] of Object.entries(partial))
  files[rel] = fillBlocks(readFileSync(join(docs, rel), "utf8"), blocks, rel);

for (const [rel, content] of Object.entries(files)) {
  const dest = join(outDir, rel);
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, content);
}
console.log(`wrote ${Object.keys(files).sort().join(", ")}`);
