// Generated by scripts/gen-telemetry.mjs from telemetry/registry; do not edit. Run `make gen`.

/** The semantic-conventions release the registry is pinned to. */
export const SEMCONV_VERSION = "v1.43.0";

// ynm's attributes
export const ATTR_YNM_OUTCOME = "ynm.outcome";
export const ATTR_YNM_OUTCOME_VALUE_OK = "ok";
export const ATTR_YNM_OUTCOME_VALUE_ERROR = "error";
export const ATTR_YNM_OUTCOME_VALUE_REFUSED = "refused";
export const ATTR_YNM_COMMAND_NAME = "ynm.command.name";
export const ATTR_YNM_STORE_OPERATION = "ynm.store.operation";
export const ATTR_YNM_STORE_OPERATION_VALUE_APPEND = "append";
export const ATTR_YNM_STORE_OPERATION_VALUE_SCAN = "scan";
export const ATTR_YNM_STORE_OPERATION_VALUE_PURGE = "purge";
export const ATTR_YNM_STORE_OPERATION_VALUE_SYNC = "sync";
export const ATTR_YNM_STORE_OPERATION_VALUE_READ_DOCUMENT = "read_document";
export const ATTR_YNM_STORE_OPERATION_VALUE_WRITE_DOCUMENT = "write_document";
export const ATTR_YNM_STORE_PROVIDER = "ynm.store.provider";
export const ATTR_YNM_MOUNT = "ynm.mount";
export const ATTR_YNM_LEVEL = "ynm.level";
export const ATTR_YNM_LEVEL_VALUE_PERSONAL = "personal";
export const ATTR_YNM_LEVEL_VALUE_DISTRIBUTED = "distributed";
export const ATTR_YNM_NAMESPACE = "ynm.namespace";
export const ATTR_YNM_RECORD_COUNT = "ynm.record.count";
export const ATTR_YNM_RESULT_COUNT = "ynm.result.count";
export const ATTR_YNM_INPUT_BYTES = "ynm.input.bytes";
export const ATTR_YNM_MEMORY_IDS = "ynm.memory.ids";
export const ATTR_YNM_DREAM_PASS = "ynm.dream.pass";
export const ATTR_YNM_DREAM_PASS_VALUE_EXPIRE = "expire";
export const ATTR_YNM_DREAM_PASS_VALUE_RETENTION = "retention";
export const ATTR_YNM_DREAM_PASS_VALUE_PROMOTE = "promote";
export const ATTR_YNM_DREAM_PASS_VALUE_DEDUPE = "dedupe";
export const ATTR_YNM_DREAM_PASS_VALUE_CONTRADICT = "contradict";
export const ATTR_YNM_DREAM_PASS_VALUE_REFLECT = "reflect";
export const ATTR_YNM_DREAM_PASS_VALUE_NORMALISE = "normalise";
export const ATTR_YNM_DREAM_DRY_RUN = "ynm.dream.dry_run";
export const ATTR_YNM_DREAM_JUDGE = "ynm.dream.judge";
export const ATTR_YNM_DREAM_FRESH = "ynm.dream.fresh";
export const ATTR_YNM_DREAM_DREAMED = "ynm.dream.dreamed";
export const ATTR_YNM_DREAM_CANDIDATES = "ynm.dream.candidates";
export const ATTR_YNM_DREAM_JUDGED = "ynm.dream.judged";
export const ATTR_YNM_DREAM_CHANGED = "ynm.dream.changed";
export const ATTR_YNM_DREAM_FLAGGED = "ynm.dream.flagged";
export const ATTR_YNM_ACTOR_KIND = "ynm.actor.kind";
export const ATTR_YNM_ACTOR_KIND_VALUE_HUMAN = "human";
export const ATTR_YNM_ACTOR_KIND_VALUE_BOT = "bot";
export const ATTR_YNM_CLIENT_ID = "ynm.client.id";
export const ATTR_YNM_AUDIT_ID = "ynm.audit.id";
export const ATTR_YNM_AUDIT_REASON = "ynm.audit.reason";
export const ATTR_YNM_AUDIT_TOOLS = "ynm.audit.tools";
export const ATTR_YNM_AUDIT_CALL_COUNT = "ynm.audit.call.count";
export const ATTR_YNM_AUDIT_ERROR_COUNT = "ynm.audit.error.count";
export const ATTR_YNM_AUDIT_DURATION_MS = "ynm.audit.duration_ms";
export const ATTR_YNM_TELEMETRY_SIGNAL = "ynm.telemetry.signal";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_TRACES = "traces";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_LOGS = "logs";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_METRICS = "metrics";

// Upstream attributes ynm uses (semantic conventions v1.43.0)
export const ATTR_ERROR_TYPE = "error.type";
export const ATTR_GEN_AI_OPERATION_NAME = "gen_ai.operation.name";
export const ATTR_GEN_AI_TOOL_NAME = "gen_ai.tool.name";
export const ATTR_HTTP_REQUEST_METHOD = "http.request.method";
export const ATTR_HTTP_RESPONSE_STATUS_CODE = "http.response.status_code";
export const ATTR_HTTP_ROUTE = "http.route";
export const ATTR_MCP_METHOD_NAME = "mcp.method.name";
export const ATTR_URL_PATH = "url.path";
export const ATTR_USER_NAME = "user.name";

// Events
export const EVENT_YNM_REQUEST_STARTED = "ynm.request.started";
export const EVENT_YNM_TOOL_STARTED = "ynm.tool.started";
export const EVENT_YNM_COMMAND_STARTED = "ynm.command.started";
export const EVENT_YNM_STORE_STARTED = "ynm.store.started";
export const EVENT_YNM_DREAM_STARTED = "ynm.dream.started";
export const EVENT_YNM_DREAM_PASS_STARTED = "ynm.dream.pass.started";
export const EVENT_YNM_AUDIT_REQUEST = "ynm.audit.request";

// Metrics
export const METRIC_YNM_HTTP_REQUEST_DURATION = "ynm.http.request.duration";
export const METRIC_YNM_TOOL_CALL_DURATION = "ynm.tool.call.duration";
export const METRIC_YNM_COMMAND_DURATION = "ynm.command.duration";
export const METRIC_YNM_STORE_OPERATION_DURATION = "ynm.store.operation.duration";
export const METRIC_YNM_DREAM_PASS_DURATION = "ynm.dream.pass.duration";
export const METRIC_YNM_TELEMETRY_EXPORT_FAILURES = "ynm.telemetry.export.failures";
export const METRIC_YNM_TELEMETRY_SPOOL_DROPPED = "ynm.telemetry.spool.dropped";
export const METRIC_YNM_TELEMETRY_SPOOL_ERRORS = "ynm.telemetry.spool.errors";

/** Each metric's declared cardinality limit, which the SDK enforces. */
export const METRIC_CARDINALITY_LIMITS: Readonly<Record<string, number>> = {
  "ynm.http.request.duration": 1920,
  "ynm.tool.call.duration": 48,
  "ynm.command.duration": 96,
  "ynm.store.operation.duration": 144,
  "ynm.dream.pass.duration": 21,
  "ynm.telemetry.export.failures": 3,
  "ynm.telemetry.spool.dropped": 1,
  "ynm.telemetry.spool.errors": 1
};

/** The whole registry, as `ynm telemetry registry --format json` prints it. */
export const REGISTRY = {
  "name": "ynm",
  "description": "Telemetry names emitted by ynm, persistent memory for coding agents.",
  "semconv_version": "v1.43.0",
  "schema_base_url": "https://github.com/eyelock/ynm/tree/develop/telemetry/registry",
  "dependencies": [
    {
      "name": "otel",
      "registry_path": "https://github.com/open-telemetry/semantic-conventions/archive/refs/tags/v1.43.0.zip[model]"
    }
  ],
  "groups": [
    {
      "id": "registry.ynm",
      "type": "attribute_group",
      "display_name": "ynm attributes",
      "brief": "Attributes owned by ynm.",
      "attributes": [
        {
          "id": "ynm.outcome",
          "type": {
            "members": [
              {
                "id": "ok",
                "value": "ok",
                "brief": "The unit of work did what was asked.",
                "stability": "development"
              },
              {
                "id": "error",
                "value": "error",
                "brief": "The unit of work failed.",
                "stability": "development"
              },
              {
                "id": "refused",
                "value": "refused",
                "brief": "The request was refused before any work, for want of a valid token or scope.",
                "stability": "development"
              }
            ]
          },
          "brief": "How a unit of work ended, in ynm's own vocabulary. Span status is set from it.",
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 3
            }
          }
        },
        {
          "id": "ynm.command.name",
          "type": "string",
          "brief": "The CLI command that ran, such as `recall` or `dream`.",
          "examples": [
            "recall",
            "dream"
          ],
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 32
            }
          }
        },
        {
          "id": "ynm.store.operation",
          "type": {
            "members": [
              {
                "id": "append",
                "value": "append",
                "brief": "Records appended to a log.",
                "stability": "development"
              },
              {
                "id": "scan",
                "value": "scan",
                "brief": "Records read from a log's shards.",
                "stability": "development"
              },
              {
                "id": "purge",
                "value": "purge",
                "brief": "Every line of one memory removed.",
                "stability": "development"
              },
              {
                "id": "sync",
                "value": "sync",
                "brief": "The log replicated with its remote.",
                "stability": "development"
              },
              {
                "id": "read_document",
                "value": "read_document",
                "brief": "A named document beside the records read.",
                "stability": "development"
              },
              {
                "id": "write_document",
                "value": "write_document",
                "brief": "A named document beside the records written.",
                "stability": "development"
              }
            ]
          },
          "brief": "What a call to a record store did.",
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 6
            }
          }
        },
        {
          "id": "ynm.store.provider",
          "type": "string",
          "brief": "The record store provider behind a mount.",
          "examples": [
            "git-notes",
            "sqlite",
            "s3"
          ],
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 8
            }
          }
        },
        {
          "id": "ynm.mount",
          "type": "string",
          "brief": "The mount a store call went to, by its configured id. Never on a metric.",
          "examples": [
            "personal",
            "project"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.level",
          "type": {
            "members": [
              {
                "id": "personal",
                "value": "personal",
                "brief": "Private to one user.",
                "stability": "development"
              },
              {
                "id": "distributed",
                "value": "distributed",
                "brief": "Shared with everyone who can read the store.",
                "stability": "development"
              }
            ]
          },
          "brief": "The level of the mount a store call went to.",
          "stability": "development"
        },
        {
          "id": "ynm.namespace",
          "type": "string",
          "brief": "The namespace a store call was limited to. Namespaces can name a person, so this is sent only when the operator sets YNM_TELEMETRY_NAMESPACES=1. Never on a metric.\n",
          "examples": [
            "common",
            "org/acme"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.record.count",
          "type": "int",
          "brief": "Records appended, read or removed by a store call.",
          "examples": [
            3
          ],
          "stability": "development"
        },
        {
          "id": "ynm.result.count",
          "type": "int",
          "brief": "Results a tool call returned, such as recall hits.",
          "examples": [
            5
          ],
          "stability": "development"
        },
        {
          "id": "ynm.input.bytes",
          "type": "int",
          "brief": "Size of a tool call's arguments as JSON, never the arguments themselves.",
          "examples": [
            212
          ],
          "stability": "development"
        },
        {
          "id": "ynm.memory.ids",
          "type": "string[]",
          "brief": "Ids of the memories a request wrote or returned.",
          "examples": [
            [
              "01K6Z9X3T2V8Q4M5N6P7R8S9TA"
            ]
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.pass",
          "type": {
            "members": [
              {
                "id": "expire",
                "value": "expire",
                "brief": "Expires memories past their time to live.",
                "stability": "development"
              },
              {
                "id": "retention",
                "value": "retention",
                "brief": "Retires old occurrences.",
                "stability": "development"
              },
              {
                "id": "promote",
                "value": "promote",
                "brief": "Promotes working memories tagged for it.",
                "stability": "development"
              },
              {
                "id": "dedupe",
                "value": "dedupe",
                "brief": "Merges restatements.",
                "stability": "development"
              },
              {
                "id": "contradict",
                "value": "contradict",
                "brief": "Supersedes or flags contradictions.",
                "stability": "development"
              },
              {
                "id": "reflect",
                "value": "reflect",
                "brief": "Writes reflections from episodes.",
                "stability": "development"
              },
              {
                "id": "normalise",
                "value": "normalise",
                "brief": "Makes relative times absolute.",
                "stability": "development"
              }
            ]
          },
          "brief": "One consolidation pass of a dream run.",
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 7
            }
          }
        },
        {
          "id": "ynm.dream.dry_run",
          "type": "boolean",
          "brief": "The dream run reported what it would do and changed nothing.",
          "stability": "development"
        },
        {
          "id": "ynm.dream.judge",
          "type": "string",
          "brief": "The judge a dream run used, by name.",
          "examples": [
            "heuristic",
            "typesafe"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.fresh",
          "type": "int",
          "brief": "Memories new or changed since a run last finished with them.",
          "examples": [
            12
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.dreamed",
          "type": "int",
          "brief": "Memories the run finished with and marked.",
          "examples": [
            12
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.candidates",
          "type": "int",
          "brief": "Memories or pairs a pass considered.",
          "examples": [
            40
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.judged",
          "type": "int",
          "brief": "Decisions a pass asked of the judge.",
          "examples": [
            8
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.changed",
          "type": "int",
          "brief": "Memories a pass changed.",
          "examples": [
            2
          ],
          "stability": "development"
        },
        {
          "id": "ynm.dream.flagged",
          "type": "int",
          "brief": "Memories a pass flagged for review.",
          "examples": [
            1
          ],
          "stability": "development"
        },
        {
          "id": "ynm.actor.kind",
          "type": {
            "members": [
              {
                "id": "human",
                "value": "human",
                "brief": "A signed-in person, named by their handle in `user.name`.",
                "stability": "development"
              },
              {
                "id": "bot",
                "value": "bot",
                "brief": "A shared static token, or a client acting with no person behind its token.",
                "stability": "development"
              }
            ]
          },
          "brief": "Who made an audited request.",
          "stability": "development"
        },
        {
          "id": "ynm.client.id",
          "type": "string",
          "brief": "The OAuth client that made a request, or `static` for a shared token.",
          "examples": [
            "claude-code",
            "static"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.id",
          "type": "string",
          "brief": "The audit event's id, the same id ynm's own audit sinks would record.",
          "examples": [
            "01K6Z9X3T2V8Q4M5N6P7R8S9TA"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.reason",
          "type": "string",
          "brief": "For a refusal, the OAuth error code. Never the token.",
          "examples": [
            "invalid_token",
            "insufficient_scope"
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.tools",
          "type": "string[]",
          "brief": "The tools a request called, in order.",
          "examples": [
            [
              "memory_recall"
            ]
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.call.count",
          "type": "int",
          "brief": "Tool calls and resource reads a request made.",
          "examples": [
            1
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.error.count",
          "type": "int",
          "brief": "Of those, how many failed.",
          "examples": [
            0
          ],
          "stability": "development"
        },
        {
          "id": "ynm.audit.duration_ms",
          "type": "int",
          "brief": "How long the request took, in milliseconds.",
          "examples": [
            23
          ],
          "stability": "development"
        },
        {
          "id": "ynm.telemetry.signal",
          "type": {
            "members": [
              {
                "id": "traces",
                "value": "traces",
                "brief": "Spans.",
                "stability": "development"
              },
              {
                "id": "logs",
                "value": "logs",
                "brief": "Log records and events.",
                "stability": "development"
              },
              {
                "id": "metrics",
                "value": "metrics",
                "brief": "Metric points.",
                "stability": "development"
              }
            ]
          },
          "brief": "Which telemetry signal an export carried.",
          "stability": "development",
          "annotations": {
            "ynm": {
              "cardinality": 3
            }
          }
        }
      ]
    },
    {
      "id": "span.ynm.http.request",
      "type": "span",
      "span_kind": "server",
      "stability": "development",
      "brief": "One HTTP request to `ynm serve --http` or the Lambda function. Named `{http.request.method} {http.route}`, or the method alone for a path outside the routes.\n",
      "attributes": [
        {
          "ref": "http.request.method"
        },
        {
          "ref": "http.route"
        },
        {
          "ref": "http.response.status_code"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "events": [
        "ynm.request.started"
      ]
    },
    {
      "id": "span.ynm.tool.call",
      "type": "span",
      "span_kind": "server",
      "stability": "development",
      "brief": "One MCP tool call, named `tools/call {gen_ai.tool.name}`.",
      "attributes": [
        {
          "ref": "mcp.method.name"
        },
        {
          "ref": "gen_ai.operation.name"
        },
        {
          "ref": "gen_ai.tool.name"
        },
        {
          "ref": "ynm.input.bytes"
        },
        {
          "ref": "ynm.result.count"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "error.type"
        }
      ],
      "events": [
        "ynm.tool.started"
      ]
    },
    {
      "id": "span.ynm.command",
      "type": "span",
      "span_kind": "internal",
      "stability": "development",
      "brief": "One CLI command, named `ynm {ynm.command.name}`. `ynm serve` and `ynm hook` have none.",
      "attributes": [
        {
          "ref": "ynm.command.name"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "error.type"
        }
      ],
      "events": [
        "ynm.command.started"
      ]
    },
    {
      "id": "span.ynm.store.operation",
      "type": "span",
      "span_kind": "client",
      "stability": "development",
      "brief": "One call to a mount's record store, named `store {ynm.store.operation}`.",
      "attributes": [
        {
          "ref": "ynm.store.operation"
        },
        {
          "ref": "ynm.store.provider"
        },
        {
          "ref": "ynm.mount"
        },
        {
          "ref": "ynm.level"
        },
        {
          "ref": "ynm.namespace"
        },
        {
          "ref": "ynm.record.count"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "error.type"
        }
      ],
      "events": [
        "ynm.store.started"
      ]
    },
    {
      "id": "span.ynm.dream.run",
      "type": "span",
      "span_kind": "internal",
      "stability": "development",
      "brief": "One dream run, named `dream`, with a child span per pass.",
      "attributes": [
        {
          "ref": "ynm.dream.dry_run"
        },
        {
          "ref": "ynm.dream.judge"
        },
        {
          "ref": "ynm.dream.fresh"
        },
        {
          "ref": "ynm.dream.dreamed"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "error.type"
        }
      ],
      "events": [
        "ynm.dream.started"
      ]
    },
    {
      "id": "span.ynm.dream.pass",
      "type": "span",
      "span_kind": "internal",
      "stability": "development",
      "brief": "One consolidation pass, named `dream {ynm.dream.pass}`.",
      "attributes": [
        {
          "ref": "ynm.dream.pass"
        },
        {
          "ref": "ynm.dream.candidates"
        },
        {
          "ref": "ynm.dream.judged"
        },
        {
          "ref": "ynm.dream.changed"
        },
        {
          "ref": "ynm.dream.flagged"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "error.type"
        }
      ],
      "events": [
        "ynm.dream.pass.started"
      ]
    },
    {
      "id": "event.ynm.request.started",
      "type": "event",
      "name": "ynm.request.started",
      "stability": "development",
      "brief": "An HTTP request began.",
      "attributes": [
        {
          "ref": "http.request.method"
        },
        {
          "ref": "http.route"
        }
      ]
    },
    {
      "id": "event.ynm.tool.started",
      "type": "event",
      "name": "ynm.tool.started",
      "stability": "development",
      "brief": "An MCP tool call began.",
      "attributes": [
        {
          "ref": "gen_ai.tool.name"
        }
      ]
    },
    {
      "id": "event.ynm.command.started",
      "type": "event",
      "name": "ynm.command.started",
      "stability": "development",
      "brief": "A CLI command began.",
      "attributes": [
        {
          "ref": "ynm.command.name"
        }
      ]
    },
    {
      "id": "event.ynm.store.started",
      "type": "event",
      "name": "ynm.store.started",
      "stability": "development",
      "brief": "A call to a record store began.",
      "attributes": [
        {
          "ref": "ynm.store.operation"
        },
        {
          "ref": "ynm.store.provider"
        },
        {
          "ref": "ynm.mount"
        }
      ]
    },
    {
      "id": "event.ynm.dream.started",
      "type": "event",
      "name": "ynm.dream.started",
      "stability": "development",
      "brief": "A dream run began.",
      "attributes": [
        {
          "ref": "ynm.dream.dry_run"
        }
      ]
    },
    {
      "id": "event.ynm.dream.pass.started",
      "type": "event",
      "name": "ynm.dream.pass.started",
      "stability": "development",
      "brief": "A consolidation pass began.",
      "attributes": [
        {
          "ref": "ynm.dream.pass"
        }
      ]
    },
    {
      "id": "event.ynm.audit.request",
      "type": "event",
      "name": "ynm.audit.request",
      "stability": "development",
      "brief": "One audited request, from the `otel` audit sink: metadata only, after the redaction patterns run. The person appears only by their handle, the sign-in id qualified by the identity provider's host, never by name or email.\n",
      "attributes": [
        {
          "ref": "ynm.audit.id"
        },
        {
          "ref": "user.name"
        },
        {
          "ref": "ynm.actor.kind"
        },
        {
          "ref": "ynm.client.id"
        },
        {
          "ref": "http.request.method"
        },
        {
          "ref": "url.path"
        },
        {
          "ref": "http.response.status_code"
        },
        {
          "ref": "ynm.outcome"
        },
        {
          "ref": "ynm.audit.reason"
        },
        {
          "ref": "ynm.audit.tools"
        },
        {
          "ref": "ynm.audit.call.count"
        },
        {
          "ref": "ynm.audit.error.count"
        },
        {
          "ref": "ynm.memory.ids"
        },
        {
          "ref": "ynm.input.bytes"
        },
        {
          "ref": "ynm.result.count"
        },
        {
          "ref": "ynm.audit.duration_ms"
        }
      ]
    },
    {
      "id": "metric.ynm.http.request.duration",
      "type": "metric",
      "metric_name": "ynm.http.request.duration",
      "instrument": "histogram",
      "unit": "s",
      "stability": "development",
      "brief": "Duration of HTTP requests.",
      "attributes": [
        {
          "ref": "http.request.method"
        },
        {
          "ref": "http.route"
        },
        {
          "ref": "http.response.status_code"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 1920,
          "attribute_cardinality": {
            "http.request.method": 10,
            "http.route": 4,
            "http.response.status_code": 16,
            "ynm.outcome": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.tool.call.duration",
      "type": "metric",
      "metric_name": "ynm.tool.call.duration",
      "instrument": "histogram",
      "unit": "s",
      "stability": "development",
      "brief": "Duration of MCP tool calls.",
      "attributes": [
        {
          "ref": "gen_ai.tool.name"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 48,
          "attribute_cardinality": {
            "gen_ai.tool.name": 16,
            "ynm.outcome": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.command.duration",
      "type": "metric",
      "metric_name": "ynm.command.duration",
      "instrument": "histogram",
      "unit": "s",
      "stability": "development",
      "brief": "Duration of CLI commands.",
      "attributes": [
        {
          "ref": "ynm.command.name"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 96,
          "attribute_cardinality": {
            "ynm.command.name": 32,
            "ynm.outcome": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.store.operation.duration",
      "type": "metric",
      "metric_name": "ynm.store.operation.duration",
      "instrument": "histogram",
      "unit": "s",
      "stability": "development",
      "brief": "Duration of calls to record stores.",
      "attributes": [
        {
          "ref": "ynm.store.operation"
        },
        {
          "ref": "ynm.store.provider"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 144,
          "attribute_cardinality": {
            "ynm.store.operation": 6,
            "ynm.store.provider": 8,
            "ynm.outcome": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.dream.pass.duration",
      "type": "metric",
      "metric_name": "ynm.dream.pass.duration",
      "instrument": "histogram",
      "unit": "s",
      "stability": "development",
      "brief": "Duration of consolidation passes.",
      "attributes": [
        {
          "ref": "ynm.dream.pass"
        },
        {
          "ref": "ynm.outcome"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 21,
          "attribute_cardinality": {
            "ynm.dream.pass": 7,
            "ynm.outcome": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.telemetry.export.failures",
      "type": "metric",
      "metric_name": "ynm.telemetry.export.failures",
      "instrument": "counter",
      "unit": "{export}",
      "stability": "development",
      "brief": "Exports that failed and were dropped. Telemetry never blocks or fails ynm, so failures are counted here instead of reported.\n",
      "attributes": [
        {
          "ref": "ynm.telemetry.signal"
        }
      ],
      "annotations": {
        "ynm": {
          "cardinality_limit": 3,
          "attribute_cardinality": {
            "ynm.telemetry.signal": 3
          }
        }
      }
    },
    {
      "id": "metric.ynm.telemetry.spool.dropped",
      "type": "metric",
      "metric_name": "ynm.telemetry.spool.dropped",
      "instrument": "counter",
      "unit": "{record}",
      "stability": "development",
      "brief": "Spans, log records and metric points the ynr spool writer did not write: its files reached their cap, one export was over the line limit, or the writer had closed. Reported only when writing to the spool.\n",
      "attributes": [],
      "annotations": {
        "ynm": {
          "cardinality_limit": 1
        }
      }
    },
    {
      "id": "metric.ynm.telemetry.spool.errors",
      "type": "metric",
      "metric_name": "ynm.telemetry.spool.errors",
      "instrument": "counter",
      "unit": "{operation}",
      "stability": "development",
      "brief": "Filesystem operations on the ynr spool that failed or ran past their time bound (a write, a flush to disk, a rotation). They are counted here, never reported. Reported only when writing to the spool.\n",
      "attributes": [],
      "annotations": {
        "ynm": {
          "cardinality_limit": 1
        }
      }
    }
  ]
} as const;
