// Generated by scripts/gen-telemetry.mjs from telemetry/registry; do not edit. Run `make gen`.

/** The semantic-conventions release the registry is pinned to. */
export const SEMCONV_VERSION = "v1.43.0";

// ynm's attributes
export const ATTR_YNM_OUTCOME = "ynm.outcome";
export const ATTR_YNM_OUTCOME_VALUE_OK = "ok";
export const ATTR_YNM_OUTCOME_VALUE_ERROR = "error";
export const ATTR_YNM_OUTCOME_VALUE_REFUSED = "refused";
export const ATTR_YNM_COMMAND_NAME = "ynm.command.name";
export const ATTR_YNM_STORE_OPERATION = "ynm.store.operation";
export const ATTR_YNM_STORE_OPERATION_VALUE_APPEND = "append";
export const ATTR_YNM_STORE_OPERATION_VALUE_SCAN = "scan";
export const ATTR_YNM_STORE_OPERATION_VALUE_PURGE = "purge";
export const ATTR_YNM_STORE_OPERATION_VALUE_SYNC = "sync";
export const ATTR_YNM_STORE_OPERATION_VALUE_READ_DOCUMENT = "read_document";
export const ATTR_YNM_STORE_OPERATION_VALUE_WRITE_DOCUMENT = "write_document";
export const ATTR_YNM_STORE_PROVIDER = "ynm.store.provider";
export const ATTR_YNM_MOUNT = "ynm.mount";
export const ATTR_YNM_LEVEL = "ynm.level";
export const ATTR_YNM_LEVEL_VALUE_PERSONAL = "personal";
export const ATTR_YNM_LEVEL_VALUE_DISTRIBUTED = "distributed";
export const ATTR_YNM_NAMESPACE = "ynm.namespace";
export const ATTR_YNM_RECORD_COUNT = "ynm.record.count";
export const ATTR_YNM_RESULT_COUNT = "ynm.result.count";
export const ATTR_YNM_INPUT_BYTES = "ynm.input.bytes";
export const ATTR_YNM_MEMORY_IDS = "ynm.memory.ids";
export const ATTR_YNM_DREAM_PASS = "ynm.dream.pass";
export const ATTR_YNM_DREAM_PASS_VALUE_EXPIRE = "expire";
export const ATTR_YNM_DREAM_PASS_VALUE_RETENTION = "retention";
export const ATTR_YNM_DREAM_PASS_VALUE_PROMOTE = "promote";
export const ATTR_YNM_DREAM_PASS_VALUE_DEDUPE = "dedupe";
export const ATTR_YNM_DREAM_PASS_VALUE_CONTRADICT = "contradict";
export const ATTR_YNM_DREAM_PASS_VALUE_REFLECT = "reflect";
export const ATTR_YNM_DREAM_PASS_VALUE_NORMALISE = "normalise";
export const ATTR_YNM_DREAM_DRY_RUN = "ynm.dream.dry_run";
export const ATTR_YNM_DREAM_JUDGE = "ynm.dream.judge";
export const ATTR_YNM_DREAM_FRESH = "ynm.dream.fresh";
export const ATTR_YNM_DREAM_DREAMED = "ynm.dream.dreamed";
export const ATTR_YNM_DREAM_CANDIDATES = "ynm.dream.candidates";
export const ATTR_YNM_DREAM_JUDGED = "ynm.dream.judged";
export const ATTR_YNM_DREAM_CHANGED = "ynm.dream.changed";
export const ATTR_YNM_DREAM_FLAGGED = "ynm.dream.flagged";
export const ATTR_YNM_ACTOR_KIND = "ynm.actor.kind";
export const ATTR_YNM_ACTOR_KIND_VALUE_HUMAN = "human";
export const ATTR_YNM_ACTOR_KIND_VALUE_BOT = "bot";
export const ATTR_YNM_CLIENT_ID = "ynm.client.id";
export const ATTR_YNM_AUDIT_ID = "ynm.audit.id";
export const ATTR_YNM_AUDIT_REASON = "ynm.audit.reason";
export const ATTR_YNM_AUDIT_TOOLS = "ynm.audit.tools";
export const ATTR_YNM_AUDIT_CALL_COUNT = "ynm.audit.call.count";
export const ATTR_YNM_AUDIT_ERROR_COUNT = "ynm.audit.error.count";
export const ATTR_YNM_AUDIT_DURATION_MS = "ynm.audit.duration_ms";
export const ATTR_YNM_MODEL_PROVIDER = "ynm.model.provider";
export const ATTR_YNM_TELEMETRY_SIGNAL = "ynm.telemetry.signal";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_TRACES = "traces";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_LOGS = "logs";
export const ATTR_YNM_TELEMETRY_SIGNAL_VALUE_METRICS = "metrics";

// Upstream attributes ynm uses (semantic conventions v1.43.0)
export const ATTR_ERROR_TYPE = "error.type";
export const ATTR_GEN_AI_OPERATION_NAME = "gen_ai.operation.name";
export const ATTR_GEN_AI_REQUEST_MODEL = "gen_ai.request.model";
export const ATTR_GEN_AI_TOOL_NAME = "gen_ai.tool.name";
export const ATTR_HTTP_REQUEST_METHOD = "http.request.method";
export const ATTR_HTTP_RESPONSE_STATUS_CODE = "http.response.status_code";
export const ATTR_HTTP_ROUTE = "http.route";
export const ATTR_MCP_METHOD_NAME = "mcp.method.name";
export const ATTR_SERVER_ADDRESS = "server.address";
export const ATTR_URL_PATH = "url.path";
export const ATTR_USER_NAME = "user.name";

// Events
export const EVENT_YNM_REQUEST_STARTED = "ynm.request.started";
export const EVENT_YNM_TOOL_STARTED = "ynm.tool.started";
export const EVENT_YNM_COMMAND_STARTED = "ynm.command.started";
export const EVENT_YNM_STORE_STARTED = "ynm.store.started";
export const EVENT_YNM_REMOTE_STARTED = "ynm.remote.started";
export const EVENT_YNM_MODEL_STARTED = "ynm.model.started";
export const EVENT_YNM_DREAM_STARTED = "ynm.dream.started";
export const EVENT_YNM_DREAM_PASS_STARTED = "ynm.dream.pass.started";
export const EVENT_YNM_AUDIT_REQUEST = "ynm.audit.request";

// Metrics
export const METRIC_YNM_HTTP_REQUEST_DURATION = "ynm.http.request.duration";
export const METRIC_YNM_TOOL_CALL_DURATION = "ynm.tool.call.duration";
export const METRIC_YNM_COMMAND_DURATION = "ynm.command.duration";
export const METRIC_YNM_STORE_OPERATION_DURATION = "ynm.store.operation.duration";
export const METRIC_YNM_REMOTE_CALL_DURATION = "ynm.remote.call.duration";
export const METRIC_YNM_MODEL_CALL_DURATION = "ynm.model.call.duration";
export const METRIC_YNM_DREAM_PASS_DURATION = "ynm.dream.pass.duration";
export const METRIC_YNM_TELEMETRY_EXPORT_FAILURES = "ynm.telemetry.export.failures";
export const METRIC_YNM_TELEMETRY_SPOOL_DROPPED = "ynm.telemetry.spool.dropped";
export const METRIC_YNM_TELEMETRY_SPOOL_ERRORS = "ynm.telemetry.spool.errors";

/** Each metric's declared cardinality limit, which the SDK enforces. */
export const METRIC_CARDINALITY_LIMITS: Readonly<Record<string, number>> = {
  "ynm.http.request.duration": 1920,
  "ynm.tool.call.duration": 48,
  "ynm.command.duration": 96,
  "ynm.store.operation.duration": 144,
  "ynm.remote.call.duration": 48,
  "ynm.model.call.duration": 12,
  "ynm.dream.pass.duration": 21,
  "ynm.telemetry.export.failures": 3,
  "ynm.telemetry.spool.dropped": 1,
  "ynm.telemetry.spool.errors": 1
};

/** The registry as `ynm telemetry registry --format json` prints it, after the tool and version. */
export const REGISTRY = {
  "semantic_conventions": {
    "name": "otel",
    "version": "1.43.0",
    "schema_url": "https://opentelemetry.io/schemas/1.43.0"
  },
  "attributes": [
    {
      "id": "ynm.outcome",
      "type": "enum",
      "members": [
        {
          "id": "ok",
          "value": "ok",
          "brief": "The unit of work did what was asked."
        },
        {
          "id": "error",
          "value": "error",
          "brief": "The unit of work failed."
        },
        {
          "id": "refused",
          "value": "refused",
          "brief": "The request was refused before any work, for want of a valid token or scope."
        }
      ],
      "brief": "How a unit of work ended, in ynm's own vocabulary. Span status is set from it.",
      "stability": "development",
      "annotations": {
        "ynm": {
          "cardinality": 3
        }
      }
    },
    {
      "id": "ynm.command.name",
      "type": "string",
      "brief": "The CLI command that ran, such as `recall` or `dream`.",
      "stability": "development",
      "examples": [
        "recall",
        "dream"
      ],
      "annotations": {
        "ynm": {
          "cardinality": 32
        }
      }
    },
    {
      "id": "ynm.store.operation",
      "type": "enum",
      "members": [
        {
          "id": "append",
          "value": "append",
          "brief": "Records appended to a log."
        },
        {
          "id": "scan",
          "value": "scan",
          "brief": "Records read from a log's shards."
        },
        {
          "id": "purge",
          "value": "purge",
          "brief": "Every line of one memory removed."
        },
        {
          "id": "sync",
          "value": "sync",
          "brief": "The log replicated with its remote."
        },
        {
          "id": "read_document",
          "value": "read_document",
          "brief": "A named document beside the records read."
        },
        {
          "id": "write_document",
          "value": "write_document",
          "brief": "A named document beside the records written."
        }
      ],
      "brief": "What a call to a record store did.",
      "stability": "development",
      "annotations": {
        "ynm": {
          "cardinality": 6
        }
      }
    },
    {
      "id": "ynm.store.provider",
      "type": "string",
      "brief": "The record store provider behind a mount.",
      "stability": "development",
      "examples": [
        "git-notes",
        "sqlite",
        "s3"
      ],
      "annotations": {
        "ynm": {
          "cardinality": 8
        }
      }
    },
    {
      "id": "ynm.mount",
      "type": "string",
      "brief": "The mount a store call went to, by its configured id. Never on a metric.",
      "stability": "development",
      "examples": [
        "personal",
        "project"
      ]
    },
    {
      "id": "ynm.level",
      "type": "enum",
      "members": [
        {
          "id": "personal",
          "value": "personal",
          "brief": "Private to one user."
        },
        {
          "id": "distributed",
          "value": "distributed",
          "brief": "Shared with everyone who can read the store."
        }
      ],
      "brief": "The level of the mount a store call went to.",
      "stability": "development"
    },
    {
      "id": "ynm.namespace",
      "type": "string",
      "brief": "The namespace a store call was limited to. Namespaces can name a person, so this is sent only when the operator sets YNM_TELEMETRY_NAMESPACES=1. Never on a metric.",
      "stability": "development",
      "examples": [
        "common",
        "org/example-org"
      ]
    },
    {
      "id": "ynm.record.count",
      "type": "int",
      "brief": "Records appended, read or removed by a store call.",
      "stability": "development",
      "examples": [
        3
      ]
    },
    {
      "id": "ynm.result.count",
      "type": "int",
      "brief": "Results a tool call returned, such as recall hits.",
      "stability": "development",
      "examples": [
        5
      ]
    },
    {
      "id": "ynm.input.bytes",
      "type": "int",
      "brief": "Size of a tool call's arguments as JSON, never the arguments themselves.",
      "stability": "development",
      "examples": [
        212
      ]
    },
    {
      "id": "ynm.memory.ids",
      "type": "string[]",
      "brief": "Ids of the memories a request wrote or returned.",
      "stability": "development",
      "examples": [
        [
          "01K6Z9X3T2V8Q4M5N6P7R8S9TA"
        ]
      ]
    },
    {
      "id": "ynm.dream.pass",
      "type": "enum",
      "members": [
        {
          "id": "expire",
          "value": "expire",
          "brief": "Expires memories past their time to live."
        },
        {
          "id": "retention",
          "value": "retention",
          "brief": "Retires old occurrences."
        },
        {
          "id": "promote",
          "value": "promote",
          "brief": "Promotes working memories tagged for it."
        },
        {
          "id": "dedupe",
          "value": "dedupe",
          "brief": "Merges restatements."
        },
        {
          "id": "contradict",
          "value": "contradict",
          "brief": "Supersedes or flags contradictions."
        },
        {
          "id": "reflect",
          "value": "reflect",
          "brief": "Writes reflections from episodes."
        },
        {
          "id": "normalise",
          "value": "normalise",
          "brief": "Makes relative times absolute."
        }
      ],
      "brief": "One consolidation pass of a dream run.",
      "stability": "development",
      "annotations": {
        "ynm": {
          "cardinality": 7
        }
      }
    },
    {
      "id": "ynm.dream.dry_run",
      "type": "boolean",
      "brief": "The dream run reported what it would do and changed nothing.",
      "stability": "development"
    },
    {
      "id": "ynm.dream.judge",
      "type": "string",
      "brief": "The judge a dream run used, by name.",
      "stability": "development",
      "examples": [
        "heuristic",
        "typesafe"
      ]
    },
    {
      "id": "ynm.dream.fresh",
      "type": "int",
      "brief": "Memories new or changed since a run last finished with them.",
      "stability": "development",
      "examples": [
        12
      ]
    },
    {
      "id": "ynm.dream.dreamed",
      "type": "int",
      "brief": "Memories the run finished with and marked.",
      "stability": "development",
      "examples": [
        12
      ]
    },
    {
      "id": "ynm.dream.candidates",
      "type": "int",
      "brief": "Memories or pairs a pass considered.",
      "stability": "development",
      "examples": [
        40
      ]
    },
    {
      "id": "ynm.dream.judged",
      "type": "int",
      "brief": "Decisions a pass asked of the judge.",
      "stability": "development",
      "examples": [
        8
      ]
    },
    {
      "id": "ynm.dream.changed",
      "type": "int",
      "brief": "Memories a pass changed.",
      "stability": "development",
      "examples": [
        2
      ]
    },
    {
      "id": "ynm.dream.flagged",
      "type": "int",
      "brief": "Memories a pass flagged for review.",
      "stability": "development",
      "examples": [
        1
      ]
    },
    {
      "id": "ynm.actor.kind",
      "type": "enum",
      "members": [
        {
          "id": "human",
          "value": "human",
          "brief": "A signed-in person, named by their handle in `user.name`."
        },
        {
          "id": "bot",
          "value": "bot",
          "brief": "A shared static token, or a client acting with no person behind its token."
        }
      ],
      "brief": "Who made an audited request.",
      "stability": "development"
    },
    {
      "id": "ynm.client.id",
      "type": "string",
      "brief": "The OAuth client that made a request, or `static` for a shared token.",
      "stability": "development",
      "examples": [
        "claude-code",
        "static"
      ]
    },
    {
      "id": "ynm.audit.id",
      "type": "string",
      "brief": "The audit event's id, the same id ynm's own audit sinks would record.",
      "stability": "development",
      "examples": [
        "01K6Z9X3T2V8Q4M5N6P7R8S9TA"
      ]
    },
    {
      "id": "ynm.audit.reason",
      "type": "string",
      "brief": "For a refusal, the OAuth error code. Never the token.",
      "stability": "development",
      "examples": [
        "invalid_token",
        "insufficient_scope"
      ]
    },
    {
      "id": "ynm.audit.tools",
      "type": "string[]",
      "brief": "The tools a request called, in order.",
      "stability": "development",
      "examples": [
        [
          "memory_recall"
        ]
      ]
    },
    {
      "id": "ynm.audit.call.count",
      "type": "int",
      "brief": "Tool calls and resource reads a request made.",
      "stability": "development",
      "examples": [
        1
      ]
    },
    {
      "id": "ynm.audit.error.count",
      "type": "int",
      "brief": "Of those, how many failed.",
      "stability": "development",
      "examples": [
        0
      ]
    },
    {
      "id": "ynm.audit.duration_ms",
      "type": "int",
      "brief": "How long the request took, in milliseconds.",
      "stability": "development",
      "examples": [
        23
      ]
    },
    {
      "id": "ynm.model.provider",
      "type": "string",
      "brief": "The model a call went to, by ynm's name for its kind: a writer (`claude-cli`, `openai-compatible`) or a judge (`typesafe`). Never the prompt or the answer.",
      "stability": "development",
      "examples": [
        "claude-cli",
        "openai-compatible",
        "typesafe"
      ],
      "annotations": {
        "ynm": {
          "cardinality": 4
        }
      }
    },
    {
      "id": "ynm.telemetry.signal",
      "type": "enum",
      "members": [
        {
          "id": "traces",
          "value": "traces",
          "brief": "Spans."
        },
        {
          "id": "logs",
          "value": "logs",
          "brief": "Log records and events."
        },
        {
          "id": "metrics",
          "value": "metrics",
          "brief": "Metric points."
        }
      ],
      "brief": "Which telemetry signal an export carried.",
      "stability": "development",
      "annotations": {
        "ynm": {
          "cardinality": 3
        }
      }
    }
  ],
  "standard_attributes": [
    "error.type",
    "gen_ai.operation.name",
    "gen_ai.request.model",
    "gen_ai.tool.name",
    "http.request.method",
    "http.response.status_code",
    "http.route",
    "mcp.method.name",
    "server.address",
    "url.path",
    "user.name"
  ],
  "spans": [
    {
      "name": "ynm.http.request",
      "kind": "server",
      "brief": "One HTTP request to `ynm serve --http` or the Lambda function. Named `{http.request.method} {http.route}`, or the method alone for a path outside the routes.",
      "attributes": [
        {
          "name": "http.request.method",
          "requirement_level": ""
        },
        {
          "name": "http.route",
          "requirement_level": ""
        },
        {
          "name": "http.response.status_code",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.tool.call",
      "kind": "server",
      "brief": "One MCP tool call, named `tools/call {gen_ai.tool.name}`.",
      "attributes": [
        {
          "name": "mcp.method.name",
          "requirement_level": ""
        },
        {
          "name": "gen_ai.operation.name",
          "requirement_level": ""
        },
        {
          "name": "gen_ai.tool.name",
          "requirement_level": ""
        },
        {
          "name": "ynm.input.bytes",
          "requirement_level": ""
        },
        {
          "name": "ynm.result.count",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.command",
      "kind": "internal",
      "brief": "One CLI command, named `ynm {ynm.command.name}`. `ynm serve` and `ynm hook` have none.",
      "attributes": [
        {
          "name": "ynm.command.name",
          "requirement_level": "",
          "cardinality": 32
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.store.operation",
      "kind": "client",
      "brief": "One call to a mount's record store, named `store {ynm.store.operation}`.",
      "attributes": [
        {
          "name": "ynm.store.operation",
          "requirement_level": "",
          "cardinality": 6
        },
        {
          "name": "ynm.store.provider",
          "requirement_level": "",
          "cardinality": 8
        },
        {
          "name": "ynm.mount",
          "requirement_level": ""
        },
        {
          "name": "ynm.level",
          "requirement_level": ""
        },
        {
          "name": "ynm.namespace",
          "requirement_level": ""
        },
        {
          "name": "ynm.record.count",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.remote.call",
      "kind": "client",
      "brief": "One tool call to a hosted ynm behind a remote mount, named `tools/call {gen_ai.tool.name}`. Its HTTP requests carry the W3C `traceparent` and `tracestate` headers, and the call its MCP `_meta`, so the hosted server's spans join this trace.",
      "attributes": [
        {
          "name": "mcp.method.name",
          "requirement_level": ""
        },
        {
          "name": "gen_ai.operation.name",
          "requirement_level": ""
        },
        {
          "name": "gen_ai.tool.name",
          "requirement_level": ""
        },
        {
          "name": "ynm.mount",
          "requirement_level": ""
        },
        {
          "name": "server.address",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.model.call",
      "kind": "client",
      "brief": "One call to a model: an invocation of the Claude CLI, or a request to an OpenAI-compatible endpoint or TypeSafe, named `model {ynm.model.provider}`. A spawned CLI gets `TRACEPARENT` for this span. The prompt and the answer are never exported.",
      "attributes": [
        {
          "name": "ynm.model.provider",
          "requirement_level": "",
          "cardinality": 4
        },
        {
          "name": "gen_ai.operation.name",
          "requirement_level": ""
        },
        {
          "name": "gen_ai.request.model",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.dream.run",
      "kind": "internal",
      "brief": "One dream run, named `dream`, with a child span per pass.",
      "attributes": [
        {
          "name": "ynm.dream.dry_run",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.judge",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.fresh",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.dreamed",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.dream.pass",
      "kind": "internal",
      "brief": "One consolidation pass, named `dream {ynm.dream.pass}`.",
      "attributes": [
        {
          "name": "ynm.dream.pass",
          "requirement_level": "",
          "cardinality": 7
        },
        {
          "name": "ynm.dream.candidates",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.judged",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.changed",
          "requirement_level": ""
        },
        {
          "name": "ynm.dream.flagged",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "error.type",
          "requirement_level": ""
        }
      ]
    }
  ],
  "events": [
    {
      "name": "ynm.request.started",
      "brief": "An HTTP request began.",
      "attributes": [
        {
          "name": "http.request.method",
          "requirement_level": ""
        },
        {
          "name": "http.route",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.tool.started",
      "brief": "An MCP tool call began.",
      "attributes": [
        {
          "name": "gen_ai.tool.name",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.command.started",
      "brief": "A CLI command began.",
      "attributes": [
        {
          "name": "ynm.command.name",
          "requirement_level": "",
          "cardinality": 32
        }
      ]
    },
    {
      "name": "ynm.store.started",
      "brief": "A call to a record store began.",
      "attributes": [
        {
          "name": "ynm.store.operation",
          "requirement_level": "",
          "cardinality": 6
        },
        {
          "name": "ynm.store.provider",
          "requirement_level": "",
          "cardinality": 8
        },
        {
          "name": "ynm.mount",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.remote.started",
      "brief": "A tool call to a hosted ynm began.",
      "attributes": [
        {
          "name": "gen_ai.tool.name",
          "requirement_level": ""
        },
        {
          "name": "ynm.mount",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.model.started",
      "brief": "A call to a model began.",
      "attributes": [
        {
          "name": "ynm.model.provider",
          "requirement_level": "",
          "cardinality": 4
        }
      ]
    },
    {
      "name": "ynm.dream.started",
      "brief": "A dream run began.",
      "attributes": [
        {
          "name": "ynm.dream.dry_run",
          "requirement_level": ""
        }
      ]
    },
    {
      "name": "ynm.dream.pass.started",
      "brief": "A consolidation pass began.",
      "attributes": [
        {
          "name": "ynm.dream.pass",
          "requirement_level": "",
          "cardinality": 7
        }
      ]
    },
    {
      "name": "ynm.audit.request",
      "brief": "One audited request, from the `otel` audit sink: metadata only, after the redaction patterns run. The person appears only by their handle: their login name at the identity provider (`preferred_username`, else the subject), qualified by its host, never a name or an email.",
      "attributes": [
        {
          "name": "ynm.audit.id",
          "requirement_level": ""
        },
        {
          "name": "user.name",
          "requirement_level": ""
        },
        {
          "name": "ynm.actor.kind",
          "requirement_level": ""
        },
        {
          "name": "ynm.client.id",
          "requirement_level": ""
        },
        {
          "name": "http.request.method",
          "requirement_level": ""
        },
        {
          "name": "url.path",
          "requirement_level": ""
        },
        {
          "name": "http.response.status_code",
          "requirement_level": ""
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        },
        {
          "name": "ynm.audit.reason",
          "requirement_level": ""
        },
        {
          "name": "ynm.audit.tools",
          "requirement_level": ""
        },
        {
          "name": "ynm.audit.call.count",
          "requirement_level": ""
        },
        {
          "name": "ynm.audit.error.count",
          "requirement_level": ""
        },
        {
          "name": "ynm.memory.ids",
          "requirement_level": ""
        },
        {
          "name": "ynm.input.bytes",
          "requirement_level": ""
        },
        {
          "name": "ynm.result.count",
          "requirement_level": ""
        },
        {
          "name": "ynm.audit.duration_ms",
          "requirement_level": ""
        }
      ]
    }
  ],
  "metrics": [
    {
      "name": "ynm.http.request.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of HTTP requests.",
      "attributes": [
        {
          "name": "http.request.method",
          "requirement_level": "",
          "cardinality": 10
        },
        {
          "name": "http.route",
          "requirement_level": "",
          "cardinality": 4
        },
        {
          "name": "http.response.status_code",
          "requirement_level": "",
          "cardinality": 16
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.tool.call.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of MCP tool calls.",
      "attributes": [
        {
          "name": "gen_ai.tool.name",
          "requirement_level": "",
          "cardinality": 16
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.command.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of CLI commands.",
      "attributes": [
        {
          "name": "ynm.command.name",
          "requirement_level": "",
          "cardinality": 32
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.store.operation.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of calls to record stores.",
      "attributes": [
        {
          "name": "ynm.store.operation",
          "requirement_level": "",
          "cardinality": 6
        },
        {
          "name": "ynm.store.provider",
          "requirement_level": "",
          "cardinality": 8
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.remote.call.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of tool calls to a hosted ynm, as the caller saw them.",
      "attributes": [
        {
          "name": "gen_ai.tool.name",
          "requirement_level": "",
          "cardinality": 16
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.model.call.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of calls to models.",
      "attributes": [
        {
          "name": "ynm.model.provider",
          "requirement_level": "",
          "cardinality": 4
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.dream.pass.duration",
      "instrument": "histogram",
      "unit": "s",
      "brief": "Duration of consolidation passes.",
      "attributes": [
        {
          "name": "ynm.dream.pass",
          "requirement_level": "",
          "cardinality": 7
        },
        {
          "name": "ynm.outcome",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.telemetry.export.failures",
      "instrument": "counter",
      "unit": "{export}",
      "brief": "Exports that failed and were dropped. Telemetry never blocks or fails ynm, so failures are counted here instead of reported.",
      "attributes": [
        {
          "name": "ynm.telemetry.signal",
          "requirement_level": "",
          "cardinality": 3
        }
      ]
    },
    {
      "name": "ynm.telemetry.spool.dropped",
      "instrument": "counter",
      "unit": "{record}",
      "brief": "Spans, log records and metric points the ynr spool writer did not write: its files reached their cap, one export was over the line limit, or the writer had closed. Reported only when writing to the spool.",
      "attributes": []
    },
    {
      "name": "ynm.telemetry.spool.errors",
      "instrument": "counter",
      "unit": "{operation}",
      "brief": "Filesystem operations on the ynr spool that failed or ran past their time bound (a write, a flush to disk, a rotation). They are counted here, never reported. Reported only when writing to the spool.",
      "attributes": []
    }
  ]
} as const;
