import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { guidance } from "@ynm/model";
import { z } from "zod";
import { TOOL_SPECS, type ToolSpec } from "../tools.js";
import { AGENTS_MD_MARKER, agentsMdBlock, delimitedBlockChange } from "./agents-md.js";
import type { Change, ClientAdapter, ClientStatus, Detection, InstallTarget } from "./types.js";
import { detectBySignals } from "./types.js";

type Json = {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  const?: unknown;
  default?: unknown;
  items?: Json;
  properties?: Record<string, Json>;
  required?: string[];
  additionalProperties?: boolean | Json;
  anyOf?: Json[];
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
};

function opts(s: Json, extra: Record<string, unknown> = {}): string {
  const o: Record<string, unknown> = { ...extra };
  if (s.description) o.description = s.description;
  if (s.default !== undefined) o.default = s.default;
  for (const k of ["minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems"] as const)
    if (s[k] !== undefined) o[k] = s[k];
  return Object.keys(o).length ? JSON.stringify(o) : "";
}

/** JSON Schema (from Zod) → TypeBox constructor source, the schema language Pi tools use. */
export function typeboxSource(s: Json): string {
  const o = (extra?: Record<string, unknown>) => {
    const t = opts(s, extra);
    return t ? `, ${t}` : "";
  };
  if (s.const !== undefined) return `Type.Literal(${JSON.stringify(s.const)}${o()})`;
  if (s.enum)
    return `Type.Union([${s.enum.map((v) => `Type.Literal(${JSON.stringify(v)})`).join(", ")}]${o()})`;
  if (s.anyOf) {
    const parts = s.anyOf.filter((x) => x.type !== "null");
    const inner =
      parts.length === 1 && parts[0]
        ? typeboxSource({ ...parts[0], description: s.description ?? parts[0].description })
        : `Type.Union([${parts.map(typeboxSource).join(", ")}]${o()})`;
    return parts.length < s.anyOf.length ? `Type.Union([${inner}, Type.Null()])` : inner;
  }
  const types = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  if (types.length === 0) return `Type.Unknown(${opts(s)})`;
  if (types.length > 1)
    return `Type.Union([${types.map((t) => typeboxSource({ ...s, type: t, description: undefined })).join(", ")}]${o()})`;
  switch (types[0]) {
    case "string":
      return `Type.String(${opts(s)})`;
    case "integer":
      return `Type.Integer(${opts(s)})`;
    case "number":
      return `Type.Number(${opts(s)})`;
    case "boolean":
      return `Type.Boolean(${opts(s)})`;
    case "null":
      return "Type.Null()";
    case "array":
      return `Type.Array(${typeboxSource(s.items ?? {})}${o()})`;
    case "object": {
      const props = Object.entries(s.properties ?? {});
      if (
        props.length === 0 &&
        s.additionalProperties &&
        typeof s.additionalProperties === "object"
      )
        return `Type.Record(Type.String(), ${typeboxSource(s.additionalProperties)}${o()})`;
      if (props.length === 0) return `Type.Record(Type.String(), Type.Unknown()${o()})`;
      const req = new Set(s.required ?? []);
      const fields = props.map(
        ([k, v]) =>
          `${JSON.stringify(k)}: ${req.has(k) ? typeboxSource(v) : `Type.Optional(${typeboxSource(v)})`}`
      );
      return `Type.Object({ ${fields.join(", ")} }${o(s.additionalProperties === false ? { additionalProperties: false } : undefined)})`;
    }
    default:
      return `Type.Any(${opts(s)})`;
  }
}

/** Source for one Pi tool: the schema in TypeBox and an `execute` that shells out to `ynm <command> --json`. */
function toolSource(spec: ToolSpec): string {
  const json = z.toJSONSchema(spec.input, { io: "input", unrepresentable: "any" }) as Json;
  const label = spec.name.replace(/^memory_/, "").replace(/_/g, " ");
  return `  pi.registerTool({
    name: ${JSON.stringify(spec.name)},
    label: ${JSON.stringify(`Memory: ${label}`)},
    description: ${JSON.stringify(spec.description)},
    parameters: ${typeboxSource(json)},
    execute: async (_toolCallId, params) => run(${JSON.stringify(spec.command)}, params as Record<string, unknown>),
  });`;
}

export const PI_EXTENSION_HEADER =
  "// Generated by ynm (`pnpm gen:clients`); do not edit. ADR-013: Pi has no MCP, so each";

/**
 * The Pi extension: one file, no dependencies beyond Pi's own TypeBox, one tool per `TOOL_SPECS`
 * entry, executed through the ynm CLI with `--json` (the concrete reason for CLI parity, ADR-008).
 */
export function piExtensionSource(): string {
  return `${PI_EXTENSION_HEADER}
// memory_* tool shells out to \`ynm <command> --json\`, so the ynm CLI must be on PATH.\n// Contract: ToolDefinition from @earendil-works/pi-coding-agent (registerTool(tool), execute(id, params)).
import { spawn } from "node:child_process";
import { Type } from "@earendil-works/pi-ai";

interface ToolResult {
  content: Array<{ type: "text"; text: string }>;
  details: unknown;
}
interface PiApi {
  registerTool(tool: {
    name: string;
    label: string;
    description: string;
    parameters: unknown;
    execute: (toolCallId: string, params: unknown) => Promise<ToolResult>;
  }): void;
}

function kebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/** Turns a params object into ynm CLI flags (mirrors the CLI's schema-derived flags). */
export function argsFor(command: string, params: Record<string, unknown>): string[] {
  const args = [command, "--json"];
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null) continue;
    const flag = \`--\${kebab(key)}\`;
    if (typeof value === "boolean") args.push(value ? flag : \`--no-\${kebab(key)}\`);
    else if (Array.isArray(value) && value.every((v) => typeof v === "string")) for (const v of value) args.push(flag, v);
    else if (typeof value === "object") args.push(flag, JSON.stringify(value));
    else args.push(flag, String(value));
  }
  return args;
}

function text(t: string, details: unknown = undefined): ToolResult {
  return { content: [{ type: "text", text: t }], details };
}

function run(command: string, params: Record<string, unknown>): Promise<ToolResult> {
  return new Promise((resolve) => {
    const child = spawn(process.env.YNM_BIN ?? "ynm", argsFor(command, params), { stdio: ["ignore", "pipe", "pipe"] });
    let out = "";
    let err = "";
    child.stdout.on("data", (d) => {
      out += d;
    });
    child.stderr.on("data", (d) => {
      err += d;
    });
    child.on("error", (e) => resolve(text(\`ynm failed to start: \${e.message}\`)));
    child.on("exit", (code) => {
      if (code !== 0) return resolve(text(\`ynm \${command} exited \${code}: \${err.trim() || out.trim()}\`));
      try {
        resolve(text(out.trim(), JSON.parse(out)));
      } catch {
        resolve(text(out.trim()));
      }
    });
  });
}

export default function ynm(pi: PiApi): void {
${(TOOL_SPECS as readonly ToolSpec[]).map(toolSource).join("\n")}
}
`;
}

/** The Pi skill (Agent Skills format): the guidance plus how to drive the CLI directly. */
export function piSkill(): string {
  return `---
name: ynm-memory
description: Use persistent memory (ynm) deliberately - recall before answering, remember decisions and preferences, supersede rather than duplicate. Tools memory_* come from the ynm extension; the same operations are available as \`ynm <command> --json\`.
---

${guidance("session-start").trim()}

${guidance("when-to-remember").trim()}

${guidance("when-to-promote").trim()}

## CLI parity

Every tool is also a command with the same flags: ${(TOOL_SPECS as readonly ToolSpec[]).map((t) => `\`ynm ${t.command}\``).join(", ")}. Add \`--json\` for machine-readable output.
`;
}

export function piDirs(t: Pick<InstallTarget, "cwd" | "home" | "scope">): {
  extension: string;
  skill: string;
} {
  const base = t.scope === "user" ? join(t.home, ".pi", "agent") : join(t.cwd, ".pi");
  return {
    extension: join(base, "extensions", "ynm.ts"),
    skill: join(base, "skills", "ynm-memory", "SKILL.md"),
  };
}

/**
 * Pi: no MCP by design, so the adapter installs the generated extension (`extensions/ynm.ts`)
 * and the skill under `~/.pi/agent/` (user) or `.pi/` (project), plus the AGENTS.md block.
 */
export const pi: ClientAdapter = {
  name: "pi",
  async detect(t): Promise<Detection> {
    return detectBySignals({ bin: "pi", user: [join(".pi", "agent")], project: [".pi"] }, t);
  },
  async plan(t: InstallTarget): Promise<Change[]> {
    const dirs = piDirs(t);
    const changes: Change[] = [];
    const ext = piExtensionSource();
    if (!existsSync(dirs.extension) || readFileSync(dirs.extension, "utf8") !== ext)
      changes.push({
        kind: "write",
        path: dirs.extension,
        content: ext,
        reason: "Pi extension exposing memory_* tools over the ynm CLI",
        label: "extension",
      });
    const skill = piSkill();
    if (!existsSync(dirs.skill) || readFileSync(dirs.skill, "utf8") !== skill)
      changes.push({
        kind: "write",
        path: dirs.skill,
        content: skill,
        reason: "ynm-memory skill",
        label: "skill",
      });
    if (t.scope === "project") {
      const c = delimitedBlockChange(
        join(t.cwd, "AGENTS.md"),
        agentsMdBlock(),
        AGENTS_MD_MARKER,
        "memory guidance for the agent (delimited block in AGENTS.md)"
      );
      if (c) changes.push(c);
    }
    return changes;
  },
  // Pi's lifecycle events belong to extensions; ynm's extension carries no hooks yet (ADR-016).
  async status({ cwd, home }): Promise<ClientStatus> {
    for (const scope of ["user", "project"] as const) {
      const dirs = piDirs({ cwd, home, scope });
      if (
        existsSync(dirs.extension) &&
        readFileSync(dirs.extension, "utf8").startsWith(PI_EXTENSION_HEADER)
      ) {
        const guided = existsSync(dirs.skill);
        return {
          client: "pi",
          configured: true,
          detail: dirs.extension,
          guidance: guided,
        };
      }
    }
    return {
      client: "pi",
      configured: false,
      detail: "extension not installed; run `ynm client install pi`",
    };
  },
};
